"""achievements up to chenyus splendor, what

Revision ID: 096517791ae8
Revises: 58d55f9de64a
Create Date: 2024-03-25 13:16:45.796651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '096517791ae8'
down_revision: Union[str, None] = '58d55f9de64a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
