"""restarting db again

Revision ID: 170e7e292a5c
Revises: 
Create Date: 2024-03-24 20:32:54.500599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '170e7e292a5c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('cat_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('primos', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('cat_id')
    )
    op.create_table('achievement',
    sa.Column('ach_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('primos', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('requirements', sa.String(), nullable=True),
    sa.Column('multiprt', sa.Integer(), nullable=True),
    sa.Column('part', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.cat_id'], ),
    sa.PrimaryKeyConstraint('ach_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('achievement')
    op.drop_table('category')
    # ### end Alembic commands ###
