"""achievements up to chenyus splendor

Revision ID: 58d55f9de64a
Revises: 170e7e292a5c
Create Date: 2024-03-25 13:15:44.447984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58d55f9de64a'
down_revision: Union[str, None] = '170e7e292a5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
